name: OpenEMR CI Setup Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    # Use MySQL as a service; GitHub Actions automatically waits until it's healthy
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: openemr_test
          MYSQL_ROOT_HOST: '%'
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10

    strategy:
      matrix:
        php: ['8.3', '8.2']

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, curl, xml, json, mysqli
          ini-values: post_max_size=256M, upload_max_filesize=256M

      # Install Composer dependencies
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      # Create MySQL test database (service hostname is available automatically)
      - name: Create MySQL test database
        run: |
          mysql -h ${{ job.services.mysql.host }} -P ${{ job.services.mysql.port }} \
            -uroot -proot -e "CREATE DATABASE IF NOT EXISTS openemr_test;"

      # Disable strict mode
      - name: Disable strict mode
        run: |
          mysql -h ${{ job.services.mysql.host }} -P ${{ job.services.mysql.port }} \
            -uroot -proot -e "SET GLOBAL sql_mode='NO_ENGINE_SUBSTITUTION';"

      # Create sqlconf.php for CI
      - name: Create sqlconf.php for CI
        run: |
          mkdir -p sites/default
          echo "<?php
          \$GLOBALS['adodb_new_link'] = 1;
          \$GLOBALS['adodb_logsql'] = true;
          \$host='${{ job.services.mysql.host }}';
          \$port=${{ job.services.mysql.port }};
          \$dbname='openemr_test';
          \$username='root';
          \$password='root';
          ?>" > sites/default/sqlconf.php

      # Import OpenEMR test database
      - name: Import OpenEMR test database
        run: |
          mysql -h ${{ job.services.mysql.host }} -P ${{ job.services.mysql.port }} \
            -uroot -proot openemr_test < sql/database.sql

      # Run PHPUnit tests
      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --configuration phpunit.xml

      # Run PHP Code Sniffer (optional)
      - name: Run PHP Code Sniffer
        run: vendor/bin/phpcs --standard=PSR12 controllers library
