name: OpenEMR CI Setup Workflows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: openemr_test
          MYSQL_ROOT_HOST: '%'
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    strategy:
      matrix:
        php: ['8.3', '8.2']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, curl, xml, json, mysqli
          ini-values: post_max_size=256M, upload_max_filesize=256M

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h127.0.0.1 -uroot -proot; do
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Create MySQL test database
        run: mysql -h127.0.0.1 -uroot -proot -e "CREATE DATABASE IF NOT EXISTS openemr_test;"

      - name: Disable strict mode for MySQL
        run: mysql -h127.0.0.1 -uroot -proot -e "SET GLOBAL sql_mode='NO_ENGINE_SUBSTITUTION';"

      - name: Create sqlconf.php for CI
        run: |
          mkdir -p sites/default
          echo "<?php
          \$GLOBALS['adodb_new_link'] = 1;
          \$GLOBALS['adodb_logsql'] = true;
          \$host='127.0.0.1';
          \$port=3306;
          \$dbname='openemr_test';
          \$username='root';
          \$password='root';
          ?>" > sites/default/sqlconf.php

      - name: Import OpenEMR test database
        run: mysql -h127.0.0.1 -uroot -proot openemr_test < sql/database.sql

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --configuration phpunit.xml

      - name: Run PHP Code Sniffer (optional)
        run: vendor/bin/phpcs --standard=PSR12 controllers library
