name: OpenEMR CI Setup Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: openemr_test
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10

    strategy:
      matrix:
        php: ['8.3', '8.2']
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, curl, xml, json, mysqli
          ini-values: post_max_size=256M, upload_max_filesize=256M

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Debug MySQL host
        run: |
          echo "MYSQL_HOST is mysql"
          echo "MYSQL_PORT is 3306"

      - name: Wait for MySQL service
        run: |
          echo "Waiting for MySQL to be ready..."
          for i in {1..30}; do
            mysqladmin ping -hmysql -uroot -proot &> /dev/null && break
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Disable strict mode for MySQL
        run: |
          mysql -hmysql -uroot -proot -e "SET GLOBAL sql_mode='NO_ENGINE_SUBSTITUTION';"

      - name: Create MySQL test database
        run: |
          mysql -hmysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS openemr_test;"

      - name: Create sqlconf.php for CI
        run: |
          mkdir -p sites/default
          echo "<?php
          \$GLOBALS['adodb_new_link'] = 1;
          \$GLOBALS['adodb_logsql'] = true;
          \$host='mysql';
          \$port=3306;
          \$dbname='openemr_test';
          \$username='root';
          \$password='root';
          ?>" > sites/default/sqlconf.php

      - name: Import OpenEMR test database
        run: |
          if [ -f sql/database.sql ]; then
            mysql -hmysql -uroot -proot openemr_test < sql/database.sql
          else
            echo "Warning: sql/database.sql not found. Skipping import."
          fi
        continue-on-error: true

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --configuration phpunit.xml

      - name: Run PHP Code Sniffer
        run: vendor/bin/phpcs --standard=PSR12 controllers library

      - name: Debug MySQL logs if something failed
        if: failure()
        run: |
          echo "=== MySQL Service Logs ==="
          docker logs $(docker ps -aqf "ancestor=mysql:8.0" | head -n1)
