name: OpenEMR CI Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: openemr_test
          MYSQL_ROOT_HOST: '%'
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10

    strategy:
      matrix:
        php: ['8.3', '8.2']
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, curl, xml, json, mysqli
          ini-values: post_max_size=256M, upload_max_filesize=256M

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Determine MySQL host
        run: |
          # GitHub Actions service hostname is the service name
          MYSQL_HOST=mysql
          MYSQL_PORT=3306
          echo "MYSQL_HOST=$MYSQL_HOST" >> $GITHUB_ENV
          echo "MYSQL_PORT=$MYSQL_PORT" >> $GITHUB_ENV
          echo "MYSQL_ROOT_PASSWORD=root" >> $GITHUB_ENV
          echo "MySQL host set to $MYSQL_HOST:$MYSQL_PORT"

      - name: Wait for MySQL service to be ready
        run: |
          echo "Waiting for MySQL at $MYSQL_HOST:$MYSQL_PORT..."
          for i in {1..30}; do
            if mysqladmin ping -h $MYSQL_HOST -P $MYSQL_PORT -uroot -proot &> /dev/null; then
              echo "MySQL is ready!"
              break
            fi
            echo "Waiting 1s..."
            sleep 1
          done

      - name: Debug MySQL connectivity
        run: |
          echo "Checking MySQL container and host resolution..."
          echo "Environment variables:"
          env | grep MYSQL
          echo "Ping MySQL container hostname '$MYSQL_HOST':"
          ping -c 4 $MYSQL_HOST || echo "Ping failed: host may be unreachable from the runner"
          echo "Try connecting with mysqladmin:"
          mysqladmin ping -h $MYSQL_HOST -uroot -proot || echo "mysqladmin cannot reach '$MYSQL_HOST'"
          echo "Check service container status (limited in GitHub runners):"
          docker ps || echo "Docker not available in this runner"
          echo "If MySQL is unreachable, check the service name and ports in your workflow."

      - name: Create MySQL test database and disable strict mode
        run: |
          mysql -h $MYSQL_HOST -P $MYSQL_PORT -uroot -proot -e "CREATE DATABASE IF NOT EXISTS openemr_test;"
          mysql -h $MYSQL_HOST -P $MYSQL_PORT -uroot -proot -e "SET GLOBAL sql_mode='NO_ENGINE_SUBSTITUTION';"

      - name: Import OpenEMR test database
        run: |
          if [ -f sql/database.sql ]; then
            mysql -h $MYSQL_HOST -P $MYSQL_PORT -uroot -proot openemr_test < sql/database.sql
          else
            echo "sql/database.sql not found. Skipping import."
          fi
        continue-on-error: true

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --configuration phpunit.xml

      - name: Run PHP Code Sniffer
        run: vendor/bin/phpcs --standard=PSR12 controllers library
