name: CI

on:
  push:
    branches: '**'
  pull_request:
    branches: [ master ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Check Java Version
        run: java -version

      - name: Build with Gradle
        run: gradle build

      - name: Run Unit Tests
        run: gradle test

      - name: Generate Code Coverage
        run: gradle jacocoTestReport

      - name: Build Docker Image
        run: docker build -t opennmr-assignment .

      - name: Run Docker Container
        run: docker run -d -p 8080:80 --name opennmr-assignment-container opennmr-assignment
      
      - name: Verify Docker Container
        run: docker ps
