name: OpenEMR CI Setup Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: openemr_test
        options: >-
          --health-cmd="mysqladmin ping -uroot -proot --silent"
          --health-interval=2s
          --health-timeout=2s
          --health-retries=5

    strategy:
      matrix:
        php: ['8.3', '8.2']

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, curl, xml, json, mysqli
          ini-values: post_max_size=256M, upload_max_filesize=256M

      # Install Composer dependencies
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      # Wait until MySQL service is ready
      - name: Wait for MySQL
        run: |
          for i in {1..15}; do
            if mysqladmin ping -hmysql -uroot -proot --silent; then
              echo "MySQL is ready"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done

      # Create MySQL test database
      - name: Create MySQL test database
        run: mysql -hmysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS openemr_test;"

      # Disable strict mode for MySQL
      - name: Disable strict mode
        run: mysql -hmysql -uroot -proot -e "SET GLOBAL sql_mode='NO_ENGINE_SUBSTITUTION';"

      # Create sqlconf.php for CI
      - name: Create sqlconf.php
        run: |
          mkdir -p sites/default
          echo "<?php
          \$GLOBALS['adodb_new_link'] = 1;
          \$GLOBALS['adodb_logsql'] = true;
          \$host='mysql';
          \$port=3306;
          \$dbname='openemr_test';
          \$username='root';
          \$password='root';
          ?>" > sites/default/sqlconf.php

      # Import OpenEMR test database
      - name: Import OpenEMR test database
        run: mysql -hmysql -uroot -proot openemr_test < sql/database.sql

      # Run PHPUnit tests
      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --configuration phpunit.xml

      # Run PHP Code Sniffer (optional)
      - name: Run PHP Code Sniffer
        run: vendor/bin/phpcs --standard=PSR12 controllers library
